name: 'Docker Build & Push'
on:
  push:
    branches:
      - 'main'

jobs:

  ## Build & Push Docker Image
  build-and-push:
    name: 'Docker Image Build & Push'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      packages: 'write'
    steps:

      ## Checkout the repository
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      ## Authenticate with the Docker Registry
      - name: 'Registry Authentication'
        uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.github_token }}'

      ## Build & Push the Docker Image
      - name: 'Build & Push Docker Image'
        uses: 'docker/build-push-action@v5.1.0'
        with:
          context: '.'
          push: true
          tags: 'ghcr.io/${{ github.repository }}:latest'
