name: 'Image Sync'

on:
  push:
    branches:
      - 'main'

jobs:

  ## Merge into the runtime branch
  merge:
    name: 'Merge'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    strategy:
      matrix:
        branch: [ 'net8.x', 'net7.x', 'net6.x' ]
    steps:

      ## We'll need to checkout our repository
      - name: 'Repository Checkout'
        uses: 'actions/checkout@v4'

      ## Merge into our branches
      - name: 'Merge into ${{ matrix.branch }}'
        uses: 'devmasx/merge-branch@master'
        with:
          type: 'now'
          target_branch: '${{ matrix.branch }}'
          message: 'Merge release ${{ github.ref_name }} into ${{ matrix.branch }}.'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
